### ISSUE TITLE
Pre-Flight Checklist for real Prod Deploy 

### ISSUE THREAD

**Issue by maxdobeck** [maxdobeck/gatekeeper#33]
https://blog.cloudflare.com/exposing-go-on-the-internet/

Got to follow all these steps.

**Comment by maxdobeck** [comment]
- [ ] TLS 1.2 via `crypto/tls`

**Set reasonable Timeouts:**
- [ ] Read Timeout
- [ ] Write Timeout
- [ ] Idle timeout
- [ ] TCP Keep Alive Timeouts: https://github.com/FiloSottile/Heartbleed/commit/4a3332ca1dc07aedf24b8540857792f72624cdf7

**Serve Mux**
- [ ] Ensure Server is setup with custom configs and meets the Serve Mux section.  `Server.Handler` should not be `nil`

**Logging**
- [ ] Ensure the Server.ErrrorLog is outputting everything so it is searchable

**Metrics**
- [ ] Monitor the number of open file descriptors

**Database Migrations**
- [ ] Auto-migrate heroku db.  More details #42
